# Generated by Django 6.0.5 on 2026-09-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_trip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="licence_plate",
            new_name="license_plate",
        ),
        migrations.AlterField(
            model_name="trip",
            name="distance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
